from datetime import datetime

# ─────────────────────────────────────────────────
#  Shared Swarm Memory — Central Agent State Store
# ─────────────────────────────────────────────────

swarm_memory: dict = {
    "last_schedule_update": None,   # Last schedule generated by Scheduler Agent
    "participants": [],             # Participants uploaded via CSV/Excel
    "generated_posts": [],          # Social posts generated by Social Media Agent
    "email_notifications": [],      # Emails sent by Email Agent
    "event_created": None,          # Last event that triggered social content
    "memory_log": [],               # Internal audit trail of all memory writes
    "activity_feed": [],            # Recent general swarm events
    "email_logs": [],               # Specific logs from Email Agent
    "social_logs": [],              # Specific logs from Social Media Agent
    "agent_status": {
        "Orchestrator": {"status": "idle", "tasks": 0},
        "Social Media Agent": {"status": "idle", "tasks": 0},
        "Email Agent": {"status": "idle", "tasks": 0},
        "Scheduler Agent": {"status": "idle", "tasks": 0},
        "Reasoning Agent": {"status": "idle", "tasks": 0},
        "Analytics Agent": {"status": "idle", "tasks": 0},
        "Crisis Agent": {"status": "idle", "tasks": 0},
        "Swarm Memory": {"status": "idle", "tasks": 0}
    }
}

def log_activity_feed(agent: str, message: str) -> None:
    entry = {
        "agent": agent,
        "message": message,
        "time": "just now", # Alternatively use actual timestamp
        "timestamp": datetime.now().isoformat()
    }
    swarm_memory["activity_feed"].insert(0, entry) # Keep newest first
    print(f"[{_ts()}] [Activity Feed] {agent}: {message}")

def log_email_agent_activity(message: str) -> None:
    swarm_memory["email_logs"].insert(0, message)
    print(f"[{_ts()}] [Email Activity] {message}")

def log_social_agent_activity(message: str) -> None:
    entry = {
        "timestamp": datetime.now().isoformat(),
        "action": message,
        "platform": "all"
    }
    swarm_memory["social_logs"].insert(0, entry)
    print(f"[{_ts()}] [Social Activity] {message}")

def update_agent_status(name: str, status: str, task_increment: int = 0):
    if name in swarm_memory["agent_status"]:
        swarm_memory["agent_status"][name]["status"] = status
        swarm_memory["agent_status"][name]["tasks"] += task_increment
        print(f"[{_ts()}] [Agent Status] {name} is now {status}")


def _ts() -> str:
    return datetime.now().strftime("%I:%M:%S %p").lstrip("0")


def update_memory(key: str, value) -> None:
    """Write a value into shared memory and log the action."""
    swarm_memory[key] = value
    entry = {"key": key, "updated_at": datetime.now().isoformat()}
    swarm_memory["memory_log"].append(entry)
    print(f"[{_ts()}] [Swarm Memory] '{key}' updated.")


def get_memory(key: str):
    """Read a value from shared memory."""
    value = swarm_memory.get(key)
    print(f"[{_ts()}] [Swarm Memory] Reading '{key}' → {type(value).__name__}")
    return value


def append_memory(key: str, value) -> None:
    """Append an item to a list stored in shared memory."""
    if key not in swarm_memory:
        swarm_memory[key] = []
    if isinstance(swarm_memory[key], list):
        swarm_memory[key].append(value)
        print(f"[{_ts()}] [Swarm Memory] Appended to '{key}'. Total: {len(swarm_memory[key])}")


def log_memory() -> None:
    """Print the full current state of swarm memory."""
    print(f"[{_ts()}] [Swarm Memory] Current state:")
    for k, v in swarm_memory.items():
        if k == "memory_log":
            print(f"  memory_log: {len(v)} entries")
        elif isinstance(v, list):
            print(f"  {k}: {len(v)} item(s)")
        else:
            print(f"  {k}: {v}")


def get_full_memory() -> dict:
    """Return a serialisable snapshot of the current swarm memory."""
    return {
        "last_schedule_update": swarm_memory.get("last_schedule_update"),
        "participants_count": len(swarm_memory.get("participants", [])),
        "generated_posts_count": len(swarm_memory.get("generated_posts", [])),
        "email_notifications_count": len(swarm_memory.get("email_notifications", [])),
        "event_created": swarm_memory.get("event_created"),
        "ai_insight": swarm_memory.get("ai_insight"),
        "memory_log": swarm_memory.get("memory_log", []),
    }
